total_station_node:
  ros__parameters:
    total_station_port: '/dev/ttyUSB0'
    total_station_verbose: True
    positional_rms: 0.005
    total_station_hz: 10
    raw_topic: '/total_station/'
    ts_prism_x_offset: 2.25 # meters
    ts_prism_y_offset: 0.00 # meters
    ts_prism_z_offset: 2.2 # meters
    ts_prism_z_rotation: 0.0 #-0.005047857 #radians
